version: "3"
services:
  monitor:
    image: lightmon
    build:
      context: .
    environment:
      - PORT=4711
      - URL=https://google.com
      - ID=5aafb4bdb21413614e8ffc91
    ports:
      - 4711:4711

      