apiVersion: v1
kind: Template
metadata:
  name: lightmon
objects:

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: lightmon

#- kind: ImageStream
#  apiVersion: v1
#  metadata:
#    name: node
#  spec:
#    dockerImageRepository: docker.io/node


- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: lightmon
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: lightmon:latest
    source:
      git:
        uri: git@github.com:twltwl/lightmon.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: node:8
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: lightmon
  spec:
    selector:
      name: lightmon
    replicas: 1
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - lightmon
        from:
          kind: ImageStreamTag
          name: lightmon:latest
    - type: ConfigChange
    template:
      metadata:
        name: lightmon
        labels:
          name: lightmon
      spec:
        containers:
        - image: lightmon
          imagePullPolicy: Always
          name: lightmon
          ports:
          - containerPort: 4711

- kind: Service
  apiVersion: v1
  metadata:
    name: lightmon
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: lightmon-fe
      port: 4711
      protocol: TCP
      targetPort: 4711
    selector:
      deploymentconfig: lightmon